### ISSUE TITLE
白鹭5.2.23版本，所有按钮点击失效

### ISSUE THREAD

**Issue by huyaoduo** [egret-labs/Egret-Inspector#9]
### 您的环境：mac

- Egret Inspector 版本：3.5
- 操作系统版本：10.14.5

### 重现步骤：

1. 5.2.23引擎项目
2. 用 Egret Inspector3.5打开游戏点击任意按钮，按钮每点一下就变扁一次，但是不触发按钮点击回调
3.用chrome或者其他浏览器打开项目正常
4.inspector3.0版本无此bug，也希望白鹭官方能提供历史版本下载的功能

### 预期行为：

能正常的运行 xxxx 功能

### 实际行为：

发生了xxx 错误，具体截图如下：
![image](https://user-images.githubusercontent.com/38173092/81470615-2c696400-921e-11ea-9cd3-18dd4dc4c3a6.png)

**Comment by huyaoduo** [comment]
断点发现event.type里能监听到begin和move，但是无法监听到end

**Comment by lizhiyu-me** [comment]
这个是很严重的bug，希望官方重视一下

**Comment by huyaoduo** [comment]
Inspector3.5.1修复这个问题了 点赞
